spring:
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:tdd-seminar
      username: sa

logging:
  level:
    org.hibernate.sql: DEBUG
